apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "wordpress.fullname" . }}-nfs-pv
  labels:
    app: wordpress
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: dyibs.synology.me
    path: /volume1/mnt/wordpress
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
